"""initial schema

Single clean initial revision for the fresh-start rollout
(docs/02-DATA-MODEL.md §7): every table from the rewritten models, plus the
hand-added Row-Level Security policies (docs/01-SYSTEM-DESIGN.md §4) that
autogenerate cannot emit. The partial unique one-director-per-institution
index is part of the model metadata (users.__table_args__) and is created
below with the users table.

Revision ID: 0001
Revises:
Create Date: 2026-07-03 21:37:01.352960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('district_code', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active','suspended')", name='ck_institutions_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_code', 'code', name='uq_institutions_district_code_code')
    )
    op.create_table('batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('identifier', sa.String(), server_default='A', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name='ck_batches_month'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'start_time', 'month', 'year', 'identifier', name='uq_batches_institution_slot')
    )
    op.create_index(op.f('ix_batches_institution_id'), 'batches', ['institution_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_institution_id'), 'courses', ['institution_id'], unique=False)
    op.create_table('id_counters',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('institution_id', 'kind', 'period')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(role = 'super_admin') = (institution_id IS NULL)", name='ck_users_super_admin_institution'),
    sa.CheckConstraint("role IN ('super_admin','institution_director','staff_manager','receptionist','staff','student')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('one_director_per_institution', 'users', ['institution_id'], unique=True, postgresql_where=sa.text("role = 'institution_director'"), sqlite_where=sa.text("role = 'institution_director'"))
    op.create_table('course_modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('module_number', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lesson_count', sa.Integer(), nullable=True),
    sa.Column('duration_hours', sa.Integer(), nullable=True),
    sa.Column('total_marks', sa.Float(), nullable=True),
    sa.Column('passing_marks', sa.Float(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('has_online_test', sa.Boolean(), nullable=True),
    sa.Column('test_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'module_number', name='uq_course_modules_course_number')
    )
    op.create_index(op.f('ix_course_modules_course_id'), 'course_modules', ['course_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('joining_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_staff_institution_id'), 'staff', ['institution_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('guardian_name', sa.String(), nullable=True),
    sa.Column('guardian_phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('aadhar_number', sa.String(), nullable=True),
    sa.Column('apaar_id', sa.String(), nullable=True),
    sa.Column('last_qualification', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('enrollment_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active','completed','dropped')", name='ck_students_status'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_students_institution_batch', 'students', ['institution_id', 'batch_id'], unique=False)
    op.create_index(op.f('ix_students_institution_id'), 'students', ['institution_id'], unique=False)
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=True)
    op.create_table('certificates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('certificate_number', sa.String(), nullable=False),
    sa.Column('verification_code', sa.String(), nullable=False),
    sa.Column('issue_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_number'),
    sa.UniqueConstraint('verification_code')
    )
    op.create_index(op.f('ix_certificates_course_id'), 'certificates', ['course_id'], unique=False)
    op.create_index(op.f('ix_certificates_institution_id'), 'certificates', ['institution_id'], unique=False)
    op.create_index(op.f('ix_certificates_student_id'), 'certificates', ['student_id'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('passing_marks', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('allow_retakes', sa.Boolean(), nullable=True),
    sa.Column('max_retakes', sa.Integer(), nullable=True),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=True),
    sa.Column('shuffle_options', sa.Boolean(), nullable=True),
    sa.Column('show_result_immediately', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['course_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_course_id'), 'exams', ['course_id'], unique=False)
    op.create_index(op.f('ix_exams_institution_id'), 'exams', ['institution_id'], unique=False)
    op.create_index(op.f('ix_exams_module_id'), 'exams', ['module_id'], unique=False)
    op.create_table('fee_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('receipt_number', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_payments_course_id'), 'fee_payments', ['course_id'], unique=False)
    op.create_index(op.f('ix_fee_payments_institution_id'), 'fee_payments', ['institution_id'], unique=False)
    op.create_index('ix_fee_payments_institution_paid_at', 'fee_payments', ['institution_id', 'paid_at'], unique=False)
    op.create_index(op.f('ix_fee_payments_receipt_number'), 'fee_payments', ['receipt_number'], unique=True)
    op.create_index(op.f('ix_fee_payments_student_id'), 'fee_payments', ['student_id'], unique=False)
    op.create_table('payroll_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('days_present', sa.Integer(), nullable=True),
    sa.Column('days_half', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'month', 'year', name='uq_payroll_records_staff_month_year')
    )
    op.create_index(op.f('ix_payroll_records_institution_id'), 'payroll_records', ['institution_id'], unique=False)
    op.create_index(op.f('ix_payroll_records_staff_id'), 'payroll_records', ['staff_id'], unique=False)
    op.create_table('staff_attendance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('marked_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'date', name='uq_staff_attendance_staff_date')
    )
    op.create_index(op.f('ix_staff_attendance_date'), 'staff_attendance', ['date'], unique=False)
    op.create_index(op.f('ix_staff_attendance_institution_id'), 'staff_attendance', ['institution_id'], unique=False)
    op.create_index('ix_staff_attendance_staff_date', 'staff_attendance', ['staff_id', 'date'], unique=False)
    op.create_index(op.f('ix_staff_attendance_staff_id'), 'staff_attendance', ['staff_id'], unique=False)
    op.create_table('student_courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_student_courses_student_course')
    )
    op.create_index(op.f('ix_student_courses_course_id'), 'student_courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_student_courses_student_id'), 'student_courses', ['student_id'], unique=False)
    op.create_table('exam_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'batch_id', 'scheduled_date', name='uq_exam_schedules_exam_batch_date')
    )
    op.create_index(op.f('ix_exam_schedules_batch_id'), 'exam_schedules', ['batch_id'], unique=False)
    op.create_index(op.f('ix_exam_schedules_exam_id'), 'exam_schedules', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_schedules_institution_id'), 'exam_schedules', ['institution_id'], unique=False)
    op.create_index(op.f('ix_exam_schedules_scheduled_date'), 'exam_schedules', ['scheduled_date'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('option_a', sa.String(), nullable=False),
    sa.Column('option_b', sa.String(), nullable=False),
    sa.Column('option_c', sa.String(), nullable=False),
    sa.Column('option_d', sa.String(), nullable=False),
    sa.Column('correct_option', sa.String(length=1), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_exam_id'), 'questions', ['exam_id'], unique=False)
    op.create_table('student_module_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('marks_obtained', sa.Float(), nullable=True),
    sa.Column('exam_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('marked_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('test_attempt_id', sa.UUID(), nullable=True),
    sa.Column('auto_graded', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['student_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['course_modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'module_id', name='uq_student_module_progress_student_module')
    )
    op.create_index(op.f('ix_student_module_progress_course_id'), 'student_module_progress', ['course_id'], unique=False)
    op.create_index(op.f('ix_student_module_progress_module_id'), 'student_module_progress', ['module_id'], unique=False)
    op.create_index(op.f('ix_student_module_progress_student_id'), 'student_module_progress', ['student_id'], unique=False)
    op.create_table('exam_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_remaining_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('obtained_marks', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('total_answered', sa.Integer(), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('question_order', sa.JSON(), nullable=True),
    sa.Column('answer_order', sa.JSON(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('retake_allowed', sa.Boolean(), nullable=True),
    sa.Column('retake_allowed_by', sa.UUID(), nullable=True),
    sa.Column('retake_allowed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('in_progress','submitted','timed_out','verified')", name='ck_exam_attempts_status'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retake_allowed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['exam_schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'student_id', 'attempt_number', name='uq_exam_attempts_exam_student_attempt')
    )
    op.create_index(op.f('ix_exam_attempts_exam_id'), 'exam_attempts', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_attempts_status'), 'exam_attempts', ['status'], unique=False)
    op.create_index(op.f('ix_exam_attempts_student_id'), 'exam_attempts', ['student_id'], unique=False)
    op.create_index('ix_exam_attempts_student_status', 'exam_attempts', ['student_id', 'status'], unique=False)
    op.create_table('student_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option', sa.String(length=1), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('marks_obtained', sa.Integer(), nullable=True),
    sa.Column('marked_for_review', sa.Boolean(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_student_answers_attempt_question')
    )
    op.create_index(op.f('ix_student_answers_attempt_id'), 'student_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_student_answers_question_id'), 'student_answers', ['question_id'], unique=False)
    # ### end Alembic commands ###

    _create_rls_policies()


# ---------------------------------------------------------------------------
# Row-Level Security (docs/01-SYSTEM-DESIGN.md §4) — defense in depth.
#
# get_tenant() arms each transaction with
#   SELECT set_config('app.institution_id', '<uuid or empty>', true)
# ('' = super_admin sees everything). The app must connect as a NON-superuser,
# non-table-owner role in production (e.g. on Supabase) for the policies to
# apply; if a developer ever forgets ctx.q, the query returns 0 rows instead
# of another tenant's data.
#
# Tables WITHOUT their own institution_id are reached only through their
# RLS-protected / ctx.q-scoped parent, so they carry no policy of their own:
#   - questions, student_answers        (via exams / exam_attempts)
#   - student_courses,
#     student_module_progress           (via students)
#   - course_modules                    (via courses)
#   - refresh_tokens, users             (auth tables, queried by id/email)
#   - institutions                      (tenant root, super_admin-managed)
# exam_attempts also lacks institution_id but IS policy-protected via its
# parent exam (see below), because attempts are the hottest student-facing
# table.
# ---------------------------------------------------------------------------

# Standard tenant tables: direct institution_id comparison.
_RLS_DIRECT_TABLES = (
    "students",
    "staff",
    "exams",
    "exam_schedules",
    "fee_payments",
    "certificates",
    "batches",
    "payroll_records",
    "staff_attendance",
    "id_counters",
)

_RLS_DIRECT_POLICY = """
CREATE POLICY tenant_isolation ON {table}
  USING (institution_id = NULLIF(current_setting('app.institution_id', true), '')::uuid
         OR current_setting('app.institution_id', true) = '')
"""

# courses: institution_id NULL = global template, visible to every tenant.
_RLS_COURSES_POLICY = """
CREATE POLICY tenant_isolation ON courses
  USING (institution_id IS NULL
         OR institution_id = NULLIF(current_setting('app.institution_id', true), '')::uuid
         OR current_setting('app.institution_id', true) = '')
"""

# exam_attempts: no institution_id column — scoped via the parent exam.
_RLS_EXAM_ATTEMPTS_POLICY = """
CREATE POLICY tenant_isolation ON exam_attempts
  USING (current_setting('app.institution_id', true) = ''
         OR EXISTS (
              SELECT 1 FROM exams e
              WHERE e.id = exam_attempts.exam_id
                AND e.institution_id = NULLIF(current_setting('app.institution_id', true), '')::uuid
            ))
"""


def _create_rls_policies() -> None:
    for table in _RLS_DIRECT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(_RLS_DIRECT_POLICY.format(table=table))

    op.execute("ALTER TABLE courses ENABLE ROW LEVEL SECURITY")
    op.execute(_RLS_COURSES_POLICY)

    op.execute("ALTER TABLE exam_attempts ENABLE ROW LEVEL SECURITY")
    op.execute(_RLS_EXAM_ATTEMPTS_POLICY)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_answers_question_id'), table_name='student_answers')
    op.drop_index(op.f('ix_student_answers_attempt_id'), table_name='student_answers')
    op.drop_table('student_answers')
    op.drop_index('ix_exam_attempts_student_status', table_name='exam_attempts')
    op.drop_index(op.f('ix_exam_attempts_student_id'), table_name='exam_attempts')
    op.drop_index(op.f('ix_exam_attempts_status'), table_name='exam_attempts')
    op.drop_index(op.f('ix_exam_attempts_exam_id'), table_name='exam_attempts')
    op.drop_table('exam_attempts')
    op.drop_index(op.f('ix_student_module_progress_student_id'), table_name='student_module_progress')
    op.drop_index(op.f('ix_student_module_progress_module_id'), table_name='student_module_progress')
    op.drop_index(op.f('ix_student_module_progress_course_id'), table_name='student_module_progress')
    op.drop_table('student_module_progress')
    op.drop_index(op.f('ix_questions_exam_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_exam_schedules_scheduled_date'), table_name='exam_schedules')
    op.drop_index(op.f('ix_exam_schedules_institution_id'), table_name='exam_schedules')
    op.drop_index(op.f('ix_exam_schedules_exam_id'), table_name='exam_schedules')
    op.drop_index(op.f('ix_exam_schedules_batch_id'), table_name='exam_schedules')
    op.drop_table('exam_schedules')
    op.drop_index(op.f('ix_student_courses_student_id'), table_name='student_courses')
    op.drop_index(op.f('ix_student_courses_course_id'), table_name='student_courses')
    op.drop_table('student_courses')
    op.drop_index(op.f('ix_staff_attendance_staff_id'), table_name='staff_attendance')
    op.drop_index('ix_staff_attendance_staff_date', table_name='staff_attendance')
    op.drop_index(op.f('ix_staff_attendance_institution_id'), table_name='staff_attendance')
    op.drop_index(op.f('ix_staff_attendance_date'), table_name='staff_attendance')
    op.drop_table('staff_attendance')
    op.drop_index(op.f('ix_payroll_records_staff_id'), table_name='payroll_records')
    op.drop_index(op.f('ix_payroll_records_institution_id'), table_name='payroll_records')
    op.drop_table('payroll_records')
    op.drop_index(op.f('ix_fee_payments_student_id'), table_name='fee_payments')
    op.drop_index(op.f('ix_fee_payments_receipt_number'), table_name='fee_payments')
    op.drop_index('ix_fee_payments_institution_paid_at', table_name='fee_payments')
    op.drop_index(op.f('ix_fee_payments_institution_id'), table_name='fee_payments')
    op.drop_index(op.f('ix_fee_payments_course_id'), table_name='fee_payments')
    op.drop_table('fee_payments')
    op.drop_index(op.f('ix_exams_module_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_institution_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_course_id'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_certificates_student_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_institution_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_course_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_index(op.f('ix_students_institution_id'), table_name='students')
    op.drop_index('ix_students_institution_batch', table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_staff_institution_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_course_modules_course_id'), table_name='course_modules')
    op.drop_table('course_modules')
    op.drop_index('one_director_per_institution', table_name='users', postgresql_where=sa.text("role = 'institution_director'"), sqlite_where=sa.text("role = 'institution_director'"))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('id_counters')
    op.drop_index(op.f('ix_courses_institution_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_batches_institution_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_table('institutions')
    # ### end Alembic commands ###
